name: Update Timezone DB

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4

      - name: Run script
        run: python scripts/convert.py
